title: "Chetan Ganipineni's Notes and Research"
description: "Just some notes and research"
theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true
  
highlighter: rouge

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/